### ISSUE TITLE
Hardcoded home dir

### ISSUE THREAD

**Issue by stropitek** [cheminfo/blast-webservice#2]
https://github.com/cheminfo/blast-webservice/blob/3e05959a4dc605fc94d46bf67fbdc8e3bb169671/.github/workflows/nodejs.yml#L34

I couldn't figure out how to use the HOME env var. Did not work with ${{ env.HOME }}, althought running `ls $HOME` works.

@targos

**Comment by targos** [comment]
Why not add the blast `bin` directory to the PATH variable? This would avoid the need for a special environment variable.

**Comment by stropitek** [comment]
I thought about this, it makes sense. Would have to refactor a little bit, because I check if the directory exists before starting the server. I would have to replace this by checking that the proper executables exist

**Comment by targos** [comment]
If you don't want to do it, you can just do a multiline script:

```
      - name: Run tests
        run: |
          export BLAST_DIRECTORY_PATH="${HOME}/ncbi-blast-${BLAST_VERSION}+/bin"
          npm run test
```
